create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null,
  celular text not null,
  respuesta text not null check (respuesta in ('asistira', 'no_asistira')),
  creado_en timestamptz not null default now()
);

alter table public.rsvp_responses enable row level security;

grant select on table public.rsvp_responses to authenticated;

drop policy if exists "Permitir registrar respuestas RSVP"
on public.rsvp_responses;

drop policy if exists "Permitir consultar respuestas a usuarios autenticados"
on public.rsvp_responses;

create policy "Permitir registrar respuestas RSVP"
on public.rsvp_responses
for insert
to anon
with check (
  char_length(trim(nombre)) between 2 and 120
  and char_length(trim(cedula)) between 5 and 30
  and char_length(trim(celular)) between 7 and 30
  and respuesta in ('asistira', 'no_asistira')
  and now() <= timestamptz '2026-12-11 23:59:59-05'
);

create policy "Permitir consultar respuestas a usuarios autenticados"
on public.rsvp_responses
for select
to authenticated
using (true);
